export enum HouseholdsActions {
    GET_HOUSEHOLDS_OF_OCCUPANT_STARTED = 'GET_HOUSEHOLDS_OF_OCCUPANT_STARTED',
    GET_HOUSEHOLDS_OF_OCCUPANT_COMPLETED = 'GET_HOUSEHOLDS_OF_OCCUPANT_STARTED',
    HOUSEHOLDS_OF_OCCUPANT = 'HOUSEHOLDS_OF_OCCUPANT',
}
