export enum HouseholdsActions {
    GET_HOUSEHOLDS_OF_USER_STARTED = 'GET_HOUSEHOLDS_OF_USER_STARTED',
    GET_HOUSEHOLDS_OF_USER_COMPLETED = 'GET_HOUSEHOLDS_OF_USER_STARTED',
    HOUSEHOLDS_OF_USER = 'HOUSEHOLDS_OF_USER',
}
